version: 2.1
orbs:
  docker: circleci/docker@1.2.1
  kubernetes: circleci/kubernetes@0.11.0
jobs:
  server_pull:
    parameters:
      namespace:
        type: string
        default: 'press-test'
    executor:
      name: 'docker/docker'
    steps:
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      - run:
          name: Pull latest version of theme on PHP server
          command: kubectl -n << parameters.namespace >> exec deployment/press-php -- bash -c "composer update osulp/press-theme && apk --update add npm && cd web/themes/contrib/press-theme && npm install && npm run setup && npm run build:drupal"
      - run:
          name: Pull latest version of theme on NGINX server
          command: kubectl -n << parameters.namespace >> exec deployment/press-nginx -- bash -c "composer update osulp/press-theme && apk --update add npm && cd web/themes/contrib/press-theme && npm install && npm run setup && npm run build:drupal"
workflows:
  ci:
    jobs:
      - server_pull:
          filters:
            branches:
              only: master
